# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Open_servce.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11Open_servce.proto\x12\x08\x61nalyzer\"\'\n\x0e\x41nalyzeRequest\x12\x15\n\rfeatures_json\x18\x01 \x01(\t\"/\n\x0f\x41nalyzeResponse\x12\x1c\n\x14vulnerabilities_json\x18\x01 \x01(\t2R\n\x08\x41nalyzer\x12\x46\n\x0f\x41nalyzeContract\x12\x18.analyzer.AnalyzeRequest\x1a\x19.analyzer.AnalyzeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Open_servce_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANALYZEREQUEST']._serialized_start=31
  _globals['_ANALYZEREQUEST']._serialized_end=70
  _globals['_ANALYZERESPONSE']._serialized_start=72
  _globals['_ANALYZERESPONSE']._serialized_end=119
  _globals['_ANALYZER']._serialized_start=121
  _globals['_ANALYZER']._serialized_end=203
# @@protoc_insertion_point(module_scope)
