
services:
  gateway:
    build:
      context: ./api-gateway-code-detective
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - code-detective
      - code-detective-model
      - redis
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

  code-detective:
    build:
      context: ./code-detective
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      GRPC_SERVER_URL: "http://[::1]:50051"
    depends_on:
      - code-detective-model

  code-detective-model:
    build:
      context: ./code-detective-model
      dockerfile: Dockerfile 
    ports:
      - "50051:50051"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
