spring:
  config:
    activate:
      on-profile: dev
  cloud:
    gateway:
      routes:
        - id: code-detective
          uri: http://localhost:8081
          predicates:
            - Path=/code-detective/{segment}
          filters:
            - StripPrefix=1

        - id: code-detective-model
          uri: ws://localhost:8000 
          predicates:
            - Path=/code-detective-model/ws/{segment}
          filters:
            - StripPrefix=1

okta:
  oauth2:
    issuer: https://dev-az3di7fabdoc8vlz.uk.auth0.com/
    audience: https://safe-contracts/

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    reactor.netty: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

