# Default values for api-gateway-code-detective.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


replicaCount: 1

image:
  repository: botirk/api_gateway_vuln-detection:latest
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

env:
  SPRING_REDIS_HOST: redis.default.svc.cluster.local
  SPRING_REDIS_PORT: 6379
  SPRING_PROFILES_ACTIVE: staging

