spring:
  cloud:
    gateway:
      routes:
        - id: feature-extractor-service
          uri: http://0.0.0.0:50051
          predicates:
            - Path=/feature-extractor/**
          filters:
            - StripPrefix=1
server:
  port: 8080

